services:
  db:
    image: mariadb
    environment: # 環境変数を設定
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment: # パスワードを毎回入力するのが面倒なので環境変数で設定
      PMA_HOST: db
      PMA_USER: testuser
      PMA_PASSWORD: testpass
    ports:
      - 8080:80
    volumes:
      - phpmyadmin-data:/sessions
volumes: # データベースが持つデータを永続化する設定
  db-data:
  phpmyadmin-data:
