services:
  db:
    image: postgres
    environment: # 環境変数を設定
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    depends_on: # dbサービスが起動してからpgadmin4サービスを起動
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: samplemail.com
      PGADMIN_DEFAULT_PASSWORD: samplepass
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes: # データベースが持つデータを永続化する設定
  db-data:
  pgadmin-data:
