services:
  db:
    image: mariadb
    environment: # 環境変数を設定
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/mysql
volumes: # データベースが持つデータを永続化する設定
  db-data:
